spring:
  application:
    name: lwx-ai-agent
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agentdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-mysql.sql
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
# 自定义 PostgreSQL 配置（给 pgvector 用）
app:
  pgvector:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 123456

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.lwx.lwxaiagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug

search-api:
  api-key: b0236c51e1233e79e3c703aa360ef5a949f97c24
